name: build
on:
  pull_request:
  push:
    branches: [main]

jobs:
  run:
    name: Build Extension
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # The Chromatic action requires full access to the Git history.
          fetch-depth: 0

      # This includes the cache to speed up `npm install` in the step below.
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version-file: package.json

      - name: Install node_modules
        run: npm install

      - name: Run Build
        run: npm run build
